import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import BgPattern from '@/app/components/BgPattern'
import GlobalSessionWrapper from '@/app/components/GlobalSessionWrapper'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Chat App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={rubik.className}>
        <Toaster />
        <GlobalSessionWrapper>{children}</GlobalSessionWrapper>
      </body>
    </html>
  )
}
